version: "3.7"

services:
  ###
  # authentication-gw API
  ###
  authgw:
    image: node:18-alpine
    user: node
    command: sh -c "npm install && npm run start"
    working_dir: /app
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-virtualfinland}
      - AWS_REGION=${AWS_REGION:-eu-north-1}
    volumes:
      - ./:/app
      - $HOME/.aws:/home/node/.aws:ro
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
  ###
  # Local https
  ###
  caddy:
    image: caddy/caddy:2.6.2-alpine
    ports:
      - 80:80 # for http->https redirection
      - 443:443
    volumes:
      - ./resources/docker/caddy/config/Caddyfile:/etc/caddy/Caddyfile
      - ./resources/docker/caddy/data:/data
      - caddy_config:/config
  ###
  # Demo app
  ###
  demoApp:
    image: node:18-alpine
    user: node
    command: sh -c "npm install && npm run start"
    working_dir: /app
    environment:
      - AUTHGW_API_HOST="https://virtualfinland-authgw.localhost"
    volumes:
      - ./webapps/svelte/:/app
    ports:
      - 5000:5000
volumes:
  caddy_config:
