version: "3.7"

services:
  ###
  # authentication-gw API
  ###
  authgw:
    image: node:18-alpine
    user: node
    command: sh -c "npm install && npm run start"
    working_dir: /app
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-virtualfinland}
      - AWS_REGION=${AWS_REGION:-eu-north-1}
      - AUTHGW_ENDPOINT_URL_OVERRIDE=https://virtualfinland-authgw.localhost
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - DYNAMODB_CACHE_TABLE_NAME=${DYNAMODB_CACHE_TABLE_NAME:-authentigation-gw-CacheTable-local}
    volumes:
      - ./:/app
      - $HOME/.aws/credentials:/home/node/.aws/credentials:ro
    ports:
      - 4078:4078
    stdin_open: true
    tty: true
    labels:
      - traefik.http.routers.authgw_http.rule=Host(`virtualfinland-authgw.localhost`)
      - traefik.http.routers.authgw_http.entrypoints=web
      - traefik.http.routers.authgw_http.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.authgw.rule=Host(`virtualfinland-authgw.localhost`)
      - traefik.http.routers.authgw.entrypoints=websecure
      - traefik.http.routers.authgw.tls=true
    networks:
      - vfd-network
  ###
  # Demo app
  ###
  demoApp:
    image: node:18-alpine
    user: node
    command: sh -c "npm install && npm run start"
    working_dir: /app
    environment:
      - VITE_AUTHGW_API_URL=https://virtualfinland-authgw.localhost
    volumes:
      - ./webapps/svelte/:/app
      - ./openapi/swagger.yml:/app/public/swagger.yml
    ports:
      - 4075:5000
    labels:
      - traefik.http.routers.demoApp.rule=Host(`virtualfinland-authgw-demo.localhost`)
    networks:
      - vfd-network

networks:
  vfd-network:
    driver: bridge
    external: true