version: "3.7"

services:
  app:
    image: node:18-alpine
    user: node
    command: sh -c "npm install && whoami && npm run start"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
