version: "3.7"

services: 
  ###
  # Local https
  ###
  caddy:
    image: caddy/caddy:2.6.2-alpine
    ports:
      - 80:80 # for http->https redirection
      - 443:443
    volumes:
      - ./resources/docker/caddy/config/Caddyfile:/etc/caddy/Caddyfile
      - ./resources/docker/caddy/data:/data
      - caddy_config:/config

volumes:
  caddy_config:
