service: authentication-gw

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: eu-north-1
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/AmazonSSMFullAccess

package:
  excludeDevDependencies: false
  patterns:
    - "!*"
    - "!**"
    - "dist/**"
    - "openapi/**"
functions:
  api-app:
    handler: dist/api-app.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}
    environment:
      AWS_REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
      AUTH_PROVIDER_REDIRECT_BACK_HOST: ${env:AUTH_PROVIDER_REDIRECT_BACK_HOST, 'http://localhost:3000'}
      APP_CONTEXT_REDIRECT_FALLBACK_URL: ${env:APP_CONTEXT_REDIRECT_FALLBACK_URL, 'http://localhost:8000'}
  api-docs:
    handler: dist/api-docs.handler
    events:
      - httpApi:
          method: GET
          path: /docs/{proxy+}
