service: authentication-gw

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-north-1

package:
  excludeDevDependencies: false
  patterns:
    - "!*"
    - "!**"
    - "dist/**"
    - "openapi/**"
functions:
  api-app:
    handler: dist/api-app.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}
    environment:
      AUTH_PROVIDER_REDIRECT_BACK_HOST: ${env:AUTH_PROVIDER_REDIRECT_BACK_HOST, 'http://localhost:3000'}
      APP_CONTEXT_REDIRECT_FALLBACK_URL: ${env:APP_CONTEXT_REDIRECT_FALLBACK_URL, 'http://localhost:8000'}
      AUTHENTICATION_GW_RUNTIME_TOKEN: ${ssm:/AUTHENTICATION_GW_RUNTIME_TOKEN}
  api-docs:
    handler: dist/api-docs.handler
    events:
      - httpApi:
          method: GET
          path: /docs/{proxy+}
