service: authentication-gw

plugins:
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-north-1

package:
  excludeDevDependencies: false
  patterns:
    - "!*"
    - "!**"
    - "dist/**"

functions:
  api-app:
    handler: dist/api-app.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}
  api-docs:
    handler: dist/api-docs.handler
    events:
      - httpApi:
          method: GET
          path: /docs/{proxy+}
