openapi: 3.0.3
info:
  title: "Authentication Gateway API"
  version: 1.0.0
paths:
  "/health":
    get:
      operationId: healthCheck
      responses:
        "200":
          description: Health check response
          content:
            text/plain:
              schema:
                type: string
                example: "OK"
  "/auth/login-request":
    get:
      operationId: LoginRequest
      parameters:
        - in: query
          name: appContext
          schema:
            type: string
          required: true
          description: "Base64-encoded object with attributes: {appName: string, redirectUrl: string, guid: string}"
      responses:
        "307":
          description: Redirect to the authentication provider service
          headers:
            location:
              description: Authentication provider service URL
              schema:
                type: string

  "/auth/openid/authenticate-response":
    get:
      operationId: AuthenticateResponse
      responses:
        "307":
          description: Authentication providers callback url, redirect back to the app context, provide loginCode and provider -variables as query params
          headers:
            location:
              description: Login initiating app context URL
              schema:
                type: string
  "/auth/openid/auth-token-request":
    post:
      operationId: AuthTokenRequest
      requestBody:
        description: Retrieve the authentication token from the auth provider service
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                loginCode:
                  type: string
                provider:
                  type: string
      responses:
        "200":
          description: Auth token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
