openapi: 3.0.3
info:
  title: "Authentication Gateway API"
  version: 1.1.0
paths:
  "/":
    get:
      operationId: root
      responses:
        "303":
          description: Redirect to the API documentation
          headers:
            location:
              description: /docs/
              schema:
                type: string
  "/docs":
    get:
      operationId: swagger
      responses:
        "200":
          description: Swagger API documentation
          content:
            text/html:
              schema:
                type: string
  "/health":
    get:
      operationId: healthCheck
      responses:
        "200":
          description: Health check response
          content:
            text/plain:
              schema:
                type: string
                example: "OK"
  "/authorize":
    post:
      operationId: AuthorizeRequest
      parameters:
        - in: header
          name: Authorization
          description: "id_token as a bearer header"
          example: "Bearer asd23123czxc.a3123asdasd.zxczxc"
          required: true
          schema:
            type: string
        - in: header
          name: X-Authorization-Context
          required: false
          description: "Optional usage context"
          schema:
            type: string
      responses:
        "200":
          description: Access granted message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    default: "Access Granted"
        "401":
          description: Access denied message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    default: "Access Denied"
  "/consent/testbed/verify":
    post:
      operationId: TestbedConsentVerify
      parameters:
        - in: header
          name: X-Consent-Token
          schema:
            type: string
      responses:
        "200":
          description: Verified message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    default: "Verified"
        "401":
          description: Unverified message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    default: "Unverified"
  "/auth/openid/{provider}/authentication-request":
    get:
      operationId: OpenIdAuthenticationRequest
      parameters:
        - in: path
          description: "Auth provider ident"
          name: provider
          schema:
            type: string
          required: true
        - in: query
          name: appContext
          schema:
            type: string
          required: true
          description: "Base64Url-encoded object with attributes eg: {appName: string, redirectUrl: string}"
      responses:
        "303":
          description: Redirect to the authentication provider service
          headers:
            location:
              description: Authentication provider service URL
              schema:
                type: string
  "/auth/openid/{provider}/authenticate-response":
    get:
      operationId: OpenIdAuthenticateResponse
      parameters:
        - in: path
          description: "Auth provider ident"
          name: provider
          schema:
            type: string
          required: true
        - in: query
          name: code
          description: "Login code"
          schema:
            type: string
          required: false
        - in: query
          name: state
          description: "Login state string"
          schema:
            type: string
          required: false
        - in: query
          name: acr_values
          schema:
            type: string
          required: false
        - in: query
          name: scope
          schema:
            type: string
          required: false
        - in: query
          name: session_state
          schema:
            type: string
          required: false
        - in: query
          name: sid
          schema:
            type: string
          required: false
        - in: query
          name: nonce
          schema:
            type: string
          required: false
        - in: query
          name: error
          schema:
            type: string
          required: false
        - in: query
          name: error_description
          schema:
            type: string
          required: false
      responses:
        "303":
          description: Authentication providers callback url, redirect back to the app context, provide loginCode and provider -variables as query params
          headers:
            location:
              description: App context URL
              schema:
                type: string
  "/auth/openid/{provider}/logout-request":
    get:
      parameters:
        - in: path
          description: "Auth provider ident"
          name: provider
          schema:
            type: string
          required: true
        - in: query
          name: appContext
          schema:
            type: string
          required: true
          description: "Base64Url-encoded object with attributes eg: {appName: string, redirectUrl: string}"
        - in: query
          name: idToken
          schema:
            type: string
          required: false
          description: "Logout id_token hint"
          example: "1233ab213.1233abec213.1233abecd213"
      operationId: OpenIdLogoutRequest
      responses:
        "303":
          description: Redirect to the authentication provider services logout endpoint
          headers:
            location:
              description: Authentication provider service URL
              schema:
                type: string
  "/auth/openid/{provider}/logout-response":
    get:
      operationId: OpenIdLogoutResponse
      parameters:
        - in: path
          description: "Auth provider ident"
          name: provider
          schema:
            type: string
          required: true
        - in: query
          name: state
          schema:
            type: string
          required: false
          description: "Base64Url-encoded object with attributes eg: {appName: string, redirectUrl: string}"
      responses:
        "303":
          description: Authentication providers callback url, redirect back to the app context
          headers:
            location:
              description: App context URL
              schema:
                type: string
  "/auth/openid/{provider}/login-request":
    post:
      operationId: OpenIdLoginRequest
      parameters:
        - in: path
          description: "Auth provider ident"
          name: provider
          schema:
            type: string
          required: true
      requestBody:
        description: Retrieve the authentication token from the auth provider service
        required: true
        content:
          application/json:
            schema:
              type: object
              required: ["loginCode", "appContext"]
              properties:
                loginCode:
                  type: string
                appContext:
                  type: string
      responses:
        "200":
          description: Logged In Response
          content:
            application/json:
              schema:
                type: object
                required: ["idToken", "expiresAt", "profileData"]
                properties:
                  idToken:
                    type: string
                    example: "1233ab213.1233abec213.1233abecd213"
                  expiresAt:
                    type: string
                    format: date-time
                    example: "2022-01-30T08:30:00.123Z"
                    description: an ISO-8601 timestamp string that specifies the token expirity datetime
                  profileData:
                    type: object
                    required: ["userId"]
                    properties:
                      userId:
                        type: string
                      email:
                        type: string
                      profile:
                        type: object
                        properties:
                          sub:
                            type: string
                          inum:
                            type: string
        "401":
          description: "Logged In details retrieval failed"
          content:
            application/json:
              schema:
                type: object
                required: ["message"]
                properties:
                  message:
                    type: string
  "/auth/saml2/{provider}/authentication-request":
    get:
      operationId: Saml2AuthenticationRequest
      parameters:
        - in: path
          description: "Auth provider ident"
          name: provider
          schema:
            type: string
          required: true
        - in: query
          name: appContext
          schema:
            type: string
          required: true
          description: "Base64Url-encoded object with attributes eg: {appName: string, redirectUrl: string}"
      responses:
        "303":
          description: Redirect to the authentication provider service
          headers:
            location:
              description: Authentication provider service URL
              schema:
                type: string
  "/auth/saml2/{provider}/authenticate-response":
    post:
      operationId: Saml2AuthenticateResponse
      parameters:
        - in: path
          description: "Auth provider ident"
          name: provider
          schema:
            type: string
          required: true
      responses:
        "303":
          description: Authentication providers callback url, redirect back to the app context
          headers:
            location:
              description: App context URL
              schema:
                type: string
  "/auth/saml2/{provider}/login-request":
    post:
      operationId: Saml2LoginRequest
      parameters:
        - in: path
          description: "Auth provider ident"
          name: provider
          schema:
            type: string
          required: true
      requestBody:
        description: Retrieve the authentication token from the auth provider service
        required: true
        content:
          application/json:
            schema:
              type: object
              required: ["loginCode", "appContext"]
              properties:
                loginCode:
                  type: string
                appContext:
                  type: string
      responses:
        "200":
          description: Logged In Response
          content:
            application/json:
              schema:
                type: object
                required: ["idToken", "expiresAt", "profileData"]
                properties:
                  idToken:
                    type: string
                    example: "1233ab213.1233abec213.1233abecd213"
                  expiresAt:
                    type: string
                    format: date-time
                    example: "2022-01-30T08:30:00.123Z"
                    description: an ISO-8601 timestamp string that specifies the token expirity datetime
                  profileData:
                    type: object
                    required: ["userId", "profile", "context"]
                    properties:
                      userId:
                        type: string
                      email:
                        type: string
                      profile:
                        type: object
                        required: ["nameID"]
                        properties:
                          nameID:
                            type: string
                          email:
                            type: string
                      context:
                        type: object
                        required: ["AuthnContextClassRef"]
                        properties:
                          AuthnContextClassRef:
                            type: string
        "401":
          description: "Logged-in details retrieval failed"
          content:
            application/json:
              schema:
                type: object
                required: ["message"]
                properties:
                  message:
                    type: string
  "/auth/saml2/{provider}/logout-request":
    get:
      operationId: Saml2LogoutRequest
      parameters:
        - in: path
          description: "Auth provider ident"
          name: provider
          schema:
            type: string
          required: true
        - in: query
          name: appContext
          schema:
            type: string
          required: true
          description: "Base64Url-encoded object with attributes eg: {appName: string, redirectUrl: string}"
        - in: query
          name: idToken
          schema:
            type: string
          required: false
          description: "Logout id_token hint"
          example: "1233ab213.1233abec213.1233abecd213"
      responses:
        "303":
          description: Redirect to the authentication provider service
          headers:
            location:
              description: Authentication provider service URL
              schema:
                type: string
  "/auth/saml2/{provider}/logout-response":
    get:
      operationId: Saml2LogoutResponse
      parameters:
        - in: path
          description: "Auth provider ident"
          name: provider
          schema:
            type: string
          required: true
        - in: query
          name: SAMLResponse
          schema:
            type: string
          required: true
          description: "Logout response"
        - in: query
          name: RelayState
          schema:
            type: string
          required: true
          description: "State string"
        - in: query
          name: SigAlg
          schema:
            type: string
          required: true
          description: "SigAlg"
        - in: query
          name: Signature
          schema:
            type: string
          required: true
          description: "Signature"
      responses:
        "303":
          description: Authentication providers callback url, redirect back to the app context
          headers:
            location:
              description: App context URL
              schema:
                type: string
  "/auth/saml2/{provider}/logout":
    $ref: "#/paths/~1auth~1saml2~1{provider}~1logout-response"
  "/auth/saml2/{provider}/.well-known/jwks.json":
    get:
      operationId: Saml2WellKnownJWKSRequest
      parameters:
        - in: path
          description: "Auth provider ident"
          name: provider
          schema:
            type: string
          required: true
      responses:
        "200":
          description: .well-known/jwks.json
