openapi: 3.0.3
info:
  title: "Authentication Gateway API"
  version: 1.0.0
paths:
  "/":
    get:
      operationId: root
      responses:
        "307":
          description: Redirect to the API documentation
          headers:
            location:
              description: /docs/
              schema:
                type: string
  "/swagger":
    get:
      operationId: swagger
      responses:
        "307":
          description: Redirect to the API documentation
          headers:
            location:
              description: /docs/
              schema:
                type: string
  "/health":
    get:
      operationId: healthCheck
      responses:
        "200":
          description: Health check response
          content:
            text/plain:
              schema:
                type: string
                example: "OK"
  "/auth/openid/login-request":
    get:
      operationId: LoginRequest
      parameters:
        - in: query
          name: appContext
          schema:
            type: string
          required: true
          description: "Base64-encoded object with attributes: {appName: string, redirectUrl: string}"
        - in: query
          name: authProvider
          schema:
            type: string
            default: "sinuna"
          required: false
          description: "Auth provider name"
      responses:
        "307":
          description: Redirect to the authentication provider service
          headers:
            location:
              description: Authentication provider service URL
              schema:
                type: string

  "/auth/openid/authenticate-response":
    get:
      operationId: AuthenticateResponse
      parameters:
        - in: query
          name: code
          description: "Login code"
          schema:
            type: string
          required: true
        - in: query
          name: state
          description: "Login state string"
          schema:
            type: string
          required: true
        - in: query
          name: acr_values
          schema:
            type: string
          required: false
        - in: query
          name: scope
          schema:
            type: string
          required: false
        - in: query
          name: session_state
          schema:
            type: string
          required: false
        - in: query
          name: sid
          schema:
            type: string
          required: false
      responses:
        "307":
          description: Authentication providers callback url, redirect back to the app context, provide loginCode and provider -variables as query params
          headers:
            location:
              description: App context URL
              schema:
                type: string
  "/auth/openid/logout-request":
    get:
      parameters:
        - in: query
          name: appContext
          schema:
            type: string
          required: true
          description: "Base64-encoded object with attributes: {appName: string, redirectUrl: string}"
        - in: query
          name: authProvider
          schema:
            type: string
            default: "sinuna"
          required: false
          description: "Auth provider name"
      operationId: LogoutRequest
      responses:
        "307":
          description: Redirect to the authentication provider services logout endpoint
          headers:
            location:
              description: Authentication provider service URL
              schema:
                type: string
  "/auth/openid/logout-response":
    get:
      operationId: LogoutResponse
      responses:
        "307":
          description: Authentication providers callback url, redirect back to the app context
          headers:
            location:
              description: App context URL
              schema:
                type: string
  "/auth/openid/auth-token-request":
    post:
      operationId: AuthTokenRequest
      requestBody:
        description: Retrieve the authentication token from the auth provider service
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                loginCode:
                  type: string
                appContext:
                  type: string
      responses:
        "200":
          description: Auth token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
