openapi: 3.0.3
info:
  title: "Authentication Gateway API"
  version: 1.0.0
paths:
  "/":
    get:
      operationId: root
      responses:
        "307":
          description: Redirect to the API documentation
          headers:
            location:
              description: /docs/
              schema:
                type: string
  "/swagger":
    get:
      operationId: swagger
      responses:
        "307":
          description: Redirect to the API documentation
          headers:
            location:
              description: /docs/
              schema:
                type: string
  "/health":
    get:
      operationId: healthCheck
      responses:
        "200":
          description: Health check response
          content:
            text/plain:
              schema:
                type: string
                example: "OK"
  "/auth/authorize":
    post:
      operationId: AuthorizeRequest
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
        - in: header
          name: X-Authorization-Provider
          schema:
            type: string
        - in: header
          name: X-Authorization-Context
          schema:
            type: string
      responses:
        "200":
          description: Access granted message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    default: "Access Granted"
        "401":
          description: Access denied message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    default: "Access Denied"
  "/auth/openid/login-request":
    get:
      operationId: OpenIdLoginRequest
      parameters:
        - in: query
          name: appContext
          schema:
            type: string
          required: true
          description: "Base64-encoded object with attributes: {appName: string, redirectUrl: string}"
        - in: query
          name: provider
          schema:
            type: string
            default: "sinuna"
          required: false
          description: "Auth provider name"
      responses:
        "307":
          description: Redirect to the authentication provider service
          headers:
            location:
              description: Authentication provider service URL
              schema:
                type: string

  "/auth/openid/authenticate-response":
    get:
      operationId: OpenIdAuthenticateResponse
      parameters:
        - in: query
          name: code
          description: "Login code"
          schema:
            type: string
          required: true
        - in: query
          name: state
          description: "Login state string"
          schema:
            type: string
          required: true
        - in: query
          name: acr_values
          schema:
            type: string
          required: false
        - in: query
          name: scope
          schema:
            type: string
          required: false
        - in: query
          name: session_state
          schema:
            type: string
          required: false
        - in: query
          name: sid
          schema:
            type: string
          required: false
        - in: query
          name: nonce
          schema:
            type: string
          required: false
      responses:
        "307":
          description: Authentication providers callback url, redirect back to the app context, provide loginCode and provider -variables as query params
          headers:
            location:
              description: App context URL
              schema:
                type: string
  "/auth/openid/logout-request":
    get:
      parameters:
        - in: query
          name: appContext
          schema:
            type: string
          required: true
          description: "Base64-encoded object with attributes: {appName: string, redirectUrl: string}"
        - in: query
          name: provider
          schema:
            type: string
            default: "sinuna"
          required: false
          description: "Auth provider name"
        - in: query
          name: idToken
          schema:
            type: string
          required: false
          description: "id_token value"
      operationId: OpenIdLogoutRequest
      responses:
        "307":
          description: Redirect to the authentication provider services logout endpoint
          headers:
            location:
              description: Authentication provider service URL
              schema:
                type: string
  "/auth/openid/logout-response":
    get:
      operationId: OpenIdLogoutResponse
      parameters:
        - in: query
          name: state
          schema:
            type: string
          required: false
          description: "Base64-encoded object with attributes: {appName: string, redirectUrl: string}"
      responses:
        "307":
          description: Authentication providers callback url, redirect back to the app context
          headers:
            location:
              description: App context URL
              schema:
                type: string
  "/auth/openid/auth-token-request":
    post:
      operationId: OpenIdAuthTokenRequest
      requestBody:
        description: Retrieve the authentication token from the auth provider service
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                loginCode:
                  type: string
                appContext:
                  type: string
      responses:
        "200":
          description: Auth token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  expiresIn:
                    type: number
        "401":
          description: "Access token retrieval failed"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  "/auth/openid/user-info-request":
    post:
      operationId: OpenIdUserInfoRequest
      requestBody:
        description: Retrieve user info from the auth provider service
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                appContext:
                  type: string
      responses:
        "200":
          description: User info object
          content:
            application/json:
              schema:
                type: object
                properties:
                  sub:
                    type: string
                  inum:
                    type: string
                  email:
                    type: string
        "401":
          description: "Login invalid or expired"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  "/auth/saml2/login-request":
    get:
      operationId: Saml2LoginRequest
      parameters:
        - in: query
          name: appContext
          schema:
            type: string
          required: true
          description: "Base64-encoded object with attributes: {appName: string, redirectUrl: string}"
        - in: query
          name: provider
          schema:
            type: string
            default: "suomifi"
          required: false
          description: "Auth provider name"
      responses:
        "307":
          description: Redirect to the authentication provider service
          headers:
            location:
              description: Authentication provider service URL
              schema:
                type: string
  "/auth/saml2/authenticate-response":
    post:
      operationId: Saml2AuthenticateResponse
      responses:
        "200":
          description: Handle response from the auth provider
  "/auth/saml2/logout-request":
    get:
      operationId: Saml2LogoutRequest
      parameters:
        - in: query
          name: appContext
          schema:
            type: string
          required: true
          description: "Base64-encoded object with attributes: {appName: string, redirectUrl: string}"
        - in: query
          name: provider
          schema:
            type: string
            default: "suomifi"
          required: false
          description: "Auth provider name"
      responses:
        "307":
          description: Redirect to the authentication provider service
          headers:
            location:
              description: Authentication provider service URL
              schema:
                type: string
  "/auth/saml2/logout":
    get:
      operationId: Saml2LogoutResponse
      parameters:
        - in: query
          name: SAMLResponse
          schema:
            type: string
          required: true
          description: "Logout response"
        - in: query
          name: RelayState
          schema:
            type: string
          required: true
          description: "State string"
        - in: query
          name: SigAlg
          schema:
            type: string
          required: true
          description: "SigAlg"
        - in: query
          name: Signature
          schema:
            type: string
          required: true
          description: "Signature"
      responses:
        "307":
          description: Authentication providers callback url, redirect back to the app context
          headers:
            location:
              description: App context URL
              schema:
                type: string
  "/auth/saml2/user-info-request":
    post:
      operationId: Saml2UserInfoRequest
      requestBody:
        description: Retrieve user info from the auth provider service
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                appContext:
                  type: string
      responses:
        "200":
          description: User info object
        "401":
          description: "Login invalid or expired"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
