name: "Staging: build, test and deploy"
on:
  workflow_dispatch:

jobs:
  deploy-app:
    uses: Virtual-Finland-Development/authentication-gw/.github/workflows/build-test-deploy.yml@main
    secrets: inherit
    with:
      environment: staging
  deploy-web:
    needs: deploy-app
    uses: Virtual-Finland-Development/authentication-gw/.github/workflows/build-and-deploy-webs.yml@main
    secrets: inherit
    with:
      environment: staging
