name: "Staging: build, test and deploy"
on:
  workflow_dispatch:
    branches: ["main"]

jobs:
  deploy-staging:
    name: "Staging: build, test and deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Build, test and deploy
        uses: Virtual-Finland-Development/authentication-gw/.github/workflows/build-test-deploy.yml@main
        secrets: inherit
        with:
          environment: staging
      - name: Tag the deployment
        uses: Virtual-Finland-Development/automatic-release-action@v1.0
        with:
          environment: staging
          githubToken: ${{ secrets.GITHUB_TOKEN }}
